/* eslint-disable camelcase */
// export const castingType = [
//   { value: 'ator_exclusivo', label: 'Atores exclusivos' },
//   { value: 'ator_nao_exclusivo', label: 'Atores não exclusivos' },
//   { value: 'influencer', label: 'Influencers' },
//   { value: 'talento', label: 'Talentos' },
//   { value: 'infantil', label: 'Infantil' },
//   { value: 'criativo', label: 'Criativos' },
// ];

// export const tipoMap: Record<string, string> = {
//   ator_exclusivo: 'Ator Exclusivo',
//   ator_nao_exclusivo: 'Ator Não Exclusivo',
//   influencer: 'Influencer',
//   talento: 'Talento',
//   infantil: 'Infantil',
//   criativo: 'Criativo',
// };

export const etny = [
  { value: 'albina', label: 'Albina' },
  { value: 'amarela', label: 'Asiática / Amarela' },
  { value: 'branca', label: 'Branca / Caucasiana' },
  { value: 'india', label: 'Indígenas' },
  { value: 'negra', label: 'Negra / Preta' },
  { value: 'parda', label: 'Parda' },
];

export const etniaMap: Record<string, string> = {
  albina: 'Albina',
  amarela: 'Asiática / Amarela',
  branca: 'Branca / Caucasiana',
  india: 'Indígena',
  negra: 'Negra / Preta',
  parda: 'Parda',
};

export const banksList = [
  { value: '001', label: 'Banco do Brasil' },
  { value: '002', label: 'Banco Central do Brasil' },
  { value: '003', label: 'Banco da Amazônia' },
  { value: '004', label: 'Banco do Nordeste do Brasil' },
  { value: '007', label: 'Banco Nacional de Desenvolvimento Econômico e Social' },
  { value: '021', label: 'Banco do Estado do Espírito Santo' },
  { value: '023', label: 'Banco de Desenvolvimento de Minas Gerais' },
  { value: '025', label: 'Banco Alfa' },
  { value: '033', label: 'Banco Santander' },
  { value: '037', label: 'Banco do Estado do Pará' },
  { value: '041', label: 'Banco do Estado do Rio Grande do Sul' },
  { value: '046', label: 'Banco Regional de Desenvolvimento do Extremo Sul' },
  { value: '047', label: 'Banco do Estado de Sergipe' },
  { value: '069', label: 'Banco Crefisa S.A.' },
  { value: '070', label: 'Banco de Brasília' },
  { value: '075', label: 'Banco ABN Amro S.A.' },
  { value: '077', label: 'Banco Inter' },
  { value: '082', label: 'Banco Topázio' },
  { value: '104', label: 'Caixa Econômica Federal' },
  { value: '107', label: 'Banco BBM' },
  { value: '121', label: 'Banco Gerador' },
  { value: '184', label: 'Banco Itaú BBA' },
  { value: '208', label: 'Banco BTG Pactual' },
  { value: '212', label: 'Banco Original S.A.' },
  { value: '218', label: 'Banco Bonsucesso' },
  { value: '224', label: 'Banco Fibra' },
  { value: '237', label: 'Bradesco' },
  { value: '260', label: 'Nu Pagamentos S.A. / Nubank' },
  { value: '263', label: 'Banco Cacique' },
  { value: '265', label: 'Banco Fator' },
  { value: '318', label: 'Banco BMG' },
  { value: '320', label: 'Banco Industrial e Comercial' },
  { value: '336', label: 'Banco C6 S.A.' },
  { value: '341', label: 'Itaú Unibanco' },
  { value: '389', label: 'Banco Mercantil do Brasil' },
  { value: '422', label: 'Banco Safra' },
  { value: '473', label: 'Banco Caixa Geral - Brasil' },
  { value: '479', label: 'Banco ItaúBank' },
  { value: '604', label: 'Banco Industrial do Brasil' },
  { value: '611', label: 'Banco Paulista' },
  { value: '612', label: 'Banco Guanabara' },
  { value: '623', label: 'Banco Pan' },
  { value: '637', label: 'Banco Sofisa' },
  { value: '643', label: 'Banco Pine' },
  { value: '653', label: 'Banco Indusval' },
  { value: '654', label: 'Banco Renner' },
  { value: '655', label: 'Banco Votorantim' },
  { value: '707', label: 'Banco Daycoval' },
  { value: '712', label: 'Banco Ourinvest S.A.' },
  { value: '719', label: 'Banco Banif' },
  { value: '721', label: 'Banco Credibel' },
  { value: '738', label: 'Banco Morada' },
  { value: '741', label: 'Banco Ribeirão Preto' },
  { value: '745', label: 'Banco Citibank' },
  { value: '746', label: 'Banco Modal' },
  { value: '999', label: 'Outros' },
];

export const tipoCabelo = [
  { value: 'liso', label: 'Liso' },
  { value: 'ondulado', label: 'Ondulado' },
  { value: 'cacheado', label: 'Cacheado' },
  { value: 'crespo', label: 'Crespo' },
  { value: 'careca', label: 'Careca' },
  { value: 'outro', label: 'Outro' },
];

export const tipoCabeloMap: Record<string, string> = {
  liso: 'Liso',
  ondulado: 'Ondulado',
  cacheado: 'Cacheado',
  crespo: 'Crespo',
  careca: 'Careca',
  outro: 'Outro',
};

export const corCabelo = [
  { value: 'preto', label: 'Preto' },
  { value: 'castanho_escuro', label: 'Castanho Escuro' },
  { value: 'castanho_claro', label: 'Castanho Claro' },
  { value: 'loiro', label: 'Loiro' },
  { value: 'loiro_escuro', label: 'Loiro Escuro' },
  { value: 'ruivo', label: 'Ruivo' },
  { value: 'grisalho', label: 'Grisalho' },
  { value: 'branco', label: 'Branco' },
  { value: 'colorido', label: 'Colorido' },
  { value: 'outro', label: 'Outro' },
];

export const corCabeloMap: Record<string, string> = {
  preto: 'Preto',
  castanho_escuro: 'Castanho Escuro',
  castanho_claro: 'Castanho Claro',
  loiro: 'Loiro',
  loiro_escuro: 'Loiro Escuro',
  ruivo: 'Ruivo',
  grisalho: 'Grisalho',
  branco: 'Branco',
  colorido: 'Colorido',
  outro: 'Outro',
};

export const corOlhos = [
  { value: 'castanho', label: 'Castanho' },
  { value: 'azul', label: 'Azul' },
  { value: 'verde', label: 'Verde' },
  { value: 'preto', label: 'Preto' },
  { value: 'mel', label: 'Mel' },
  { value: 'cinza', label: 'Cinza' },
  { value: 'castanho_esverdeado', label: 'Castanho Esverdeado' },
];

export const corOlhosMap: Record<string, string> = {
  castanho: 'Castanho',
  azul: 'Azul',
  verde: 'Verde',
  preto: 'Preto',
  mel: 'Mel',
  cinza: 'Cinza',
  castanho_esverdeado: 'Castanho Esverdeado',
};

export const languages = [
  { value: 'portugues', label: 'Português' },
  { value: 'ingles', label: 'Inglês' },
  { value: 'espanhol', label: 'Espanhol' },
  { value: 'frances', label: 'Francês' },
  { value: 'italiano', label: 'Italiano' },
  { value: 'alemao', label: 'Alemão' },
  { value: 'mandarim', label: 'Mandarim' },
  { value: 'japones', label: 'Japonês' },
  { value: 'russo', label: 'Russo' },
  { value: 'arabe', label: 'Árabe' },
  { value: 'hungaro', label: 'Húngaro' },
  { value: 'outros', label: 'Outros' },
];

export const languagesMap: Record<string, string> = {
  portugues: 'Português',
  ingles: 'Inglês',
  espanhol: 'Espanhol',
  frances: 'Francês',
  italiano: 'Italiano',
  alemao: 'Alemão',
  mandarim: 'Mandarim',
  japones: 'Japonês',
  russo: 'Russo',
  arabe: 'Árabe',
  hungaro: 'Húngaro',
};

export const vehicles = [
  { value: 'carro', label: 'Carro' },
  { value: 'moto', label: 'Moto' },
  { value: 'trator', label: 'Trator' },
  { value: 'jetski', label: 'Jetski' },
  { value: 'helicoptero', label: 'Helicóptero' },
  { value: 'aviao', label: 'Avião' },
  { value: 'barco', label: 'Barco' },
];

export const genderData = [
  { value: 'masculino', label: 'Masculino' },
  { value: 'feminino', label: 'Feminino' },
  { value: 'nao_binario', label: 'Não Binário' },
];

export const genderMap: Record<string, string> = {
  masculino: 'Masculino',
  feminino: 'Feminino',
  nao_binario: 'Não Binário',
};

export const estados = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Rorâima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' },
];

export const shoeSize = [
  { value: '30', label: '30' },
  { value: '31', label: '31' },
  { value: '32', label: '32' },
  { value: '33', label: '33' },
  { value: '34', label: '34' },
  { value: '35', label: '35' },
  { value: '36', label: '36' },
  { value: '37', label: '37' },
  { value: '38', label: '38' },
  { value: '39', label: '39' },
  { value: '40', label: '40' },
  { value: '41', label: '41' },
  { value: '42', label: '42' },
  { value: '43', label: '43' },
  { value: '44', label: '44' },
  { value: '45', label: '45' },
  { value: '46', label: '46' },
  { value: '47', label: '47' },
  { value: '48', label: '48' },
  { value: '49', label: '49' },
];

export const habilidadesData = [
  { value: 'none', label: 'Sem habilidade extra' },
  { value: 'canto', label: 'Canto' },
  { value: 'danca', label: 'Dança' },
  { value: 'dublador', label: 'Dublador' },
  { value: 'locutor', label: 'Locutor' },
  { value: 'mestrecerimonia', label: 'Mestre de Cerimônia' },
  { value: 'apresentador', label: 'Apresentador' },
  { value: 'bartender', label: 'Bartender' },
  { value: 'garcom', label: 'Garçom' },
  { value: 'duble-de-acao', label: 'Dublê de Ação' },
  { value: 'manuseio-arma-fogo', label: 'Manuseio de Arma de fogo' },
  { value: 'audiodescricao', label: 'Audiodescrição' },
  { value: 'crc-acb', label: 'Circo	-	Acrobacia coletiva base' },
  { value: 'crc-aci', label: 'Circo	-	Acrobacia coletiva Intermediário' },
  { value: 'crc-acv', label: 'Circo	-	Acrobacia coletiva Volante' },
  { value: 'crc-lra', label: 'Circo	-	Lira' },
  { value: 'crc-mdc', label: 'Circo	-	Malabarismo de contato' },
  { value: 'crc-mdl', label: 'Circo	-	Malabarismo de lançamento' },
  { value: 'crc-mag', label: 'Circo	-	Malabarismo giroscópico' },
  { value: 'crc-mnc', label: 'Circo	-	Monociclo' },
  { value: 'crc-pdp', label: 'Circo	-	Perna de pau' },
  { value: 'crc-tac', label: 'Circo	-	Tecido Acrobático' },
  { value: 'crc-trf', label: 'Circo	-	Trapézio Fixo' },
  { value: 'esp-aikido', label: 'Esportes - Aikido' },
  { value: 'esp-alpinismo', label: 'Esportes - Alpinismo' },
  { value: 'esp-arco-flecha', label: 'Esportes - Arco e Flecha' },
  { value: 'esp-argolas', label: 'Esportes - Argolas (Olímpico)' },
  { value: 'esp-artdo', label: 'Esportes - ArtDo' },
  { value: 'esp-atleta-paraolímpico', label: 'Esportes - Atleta Paraolímpico' },
  { value: 'esp-atletismo', label: 'Esportes - Atletismo' },
  { value: 'esp-automobilismo', label: 'Esportes - Automobilismo' },
  { value: 'esp-badmington', label: 'Esportes - Badmington' },
  { value: 'esp-balonismo', label: 'Esportes - Balonismo' },
  {
    value: 'esp-barra-fixa-olimpico',
    label: 'Esportes - Barra fixa  (Olímpico)',
  },
  {
    value: 'esp-barra-assimetricas-olimpico',
    label: 'Esportes - Barra assimétricas (Olímpico)',
  },
  {
    value: 'esp-barra-paralelas-olimpico',
    label: 'Esportes - Barra paralelas (Olímpico)',
  },
  { value: 'esp-basebol', label: 'Esportes - Basebol' },
  { value: 'esp-basquete', label: 'Esportes - Basquete' },
  { value: 'esp-bike-freestyle', label: 'Esportes - Bike (Freestyle - BMX)' },
  { value: 'esp-bike-speed', label: 'Esportes - Bike Speed' },
  { value: 'esp-bocha', label: 'Esportes - Bocha' },
  { value: 'esp-body-combat', label: 'Esportes - Body Combat' },
  { value: 'esp-bodyboard', label: 'Esportes - Bodyboard' },
  { value: 'esp-boliche', label: 'Esportes - Boliche' },
  { value: 'esp-boxe', label: 'Esportes - Boxe' },
  { value: 'esp-bumerangue', label: 'Esportes - Bumerangue' },
  { value: 'esp-caca-esportiva', label: 'Esportes - Caça esportiva' },
  { value: 'esp-canoagem', label: 'Esportes - Canoagem' },
  { value: 'esp-capoeira', label: 'Esportes - Capoeira' },
  {
    value: 'esp-cavalo-alcas-olimpico',
    label: 'Esportes - Cavalo com alças (Olímpico)',
  },
  { value: 'esp-ciclismo', label: 'Esportes - Ciclismo' },
  { value: 'esp-corrida', label: 'Esportes - Corrida' },
  { value: 'esp-cricket', label: 'Esportes - Cricket' },
  { value: 'esp-crossfit', label: 'Esportes - Crossfit' },
  { value: 'esp-dardo', label: 'Esportes - Dardo' },
  { value: 'esp-drift-trike', label: 'Esportes - Drift Trike' },
  { value: 'esp-enduro', label: 'Esportes - Enduro' },
  { value: 'esp-equitacao', label: 'Esportes - Equitação' },
  { value: 'esp-escalada', label: 'Esportes - Escalada' },
  { value: 'esp-esgrima', label: 'Esportes - Esgrima' },
  { value: 'esp-espeleologia', label: 'Esportes - Espeleologia' },
  { value: 'esp-fisiculturismo', label: 'Esportes - Fisiculturismo' },
  { value: 'esp-fitness', label: 'Esportes - Fitness' },
  { value: 'esp-flyboard', label: 'Esportes - Flyboard' },
  { value: 'esp-frisbee', label: 'Esportes - Frisbee' },
  { value: 'esp-full-contact', label: 'Esportes - Full Contact' },
  { value: 'esp-futebol', label: 'Esportes - Futebol' },
  { value: 'esp-futebol-americano', label: 'Esportes - Futebol Americano' },
  { value: 'esp-futevolei', label: 'Esportes - Futevolêi' },
  { value: 'esp-futsal', label: 'Esportes - Futsal' },
  {
    value: 'esp-ginastica-artistica-olimpico',
    label: 'Esportes - Ginástica Artística (Olímpico)',
  },
  { value: 'esp-ginastica-laboral', label: 'Esportes - Ginástica Laboral' },
  {
    value: 'esp-ginastica-localizada',
    label: 'Esportes - Ginástica Localizada',
  },
  { value: 'esp-ginastica-natural', label: 'Esportes - Ginástica Natural' },
  { value: 'esp-ginastica-ritmica', label: 'Esportes - Ginástica Rítmica' },
  { value: 'esp-golfe', label: 'Esportes - Golfe' },
  { value: 'esp-halterofilismo', label: 'Esportes - Halterofilismo' },
  { value: 'esp-handball', label: 'Esportes - Handball' },
  { value: 'esp-hapkido', label: 'Esportes - Hapkidô' },
  { value: 'esp-hidroginastica', label: 'Esportes - Hidroginástica' },
  { value: 'esp-hipismo', label: 'Esportes - Hipismo' },
  {
    value: 'esp-hokey-campo-grama',
    label: 'Esportes - Hokey de Campo (Grama)',
  },
  { value: 'esp-hokey-gelo', label: 'Esportes - Hokey no Gelo' },
  { value: 'esp-hokey-patins', label: 'Esportes - Hokey Patins' },
  { value: 'esp-iatismo', label: 'Esportes - Iatismo / Vela' },
  { value: 'esp-jet-ski', label: 'Esportes - Jet Ski' },
  { value: 'esp-jiu-jitsu', label: 'Esportes - Jiu Jitsu' },
  { value: 'esp-jogos-medievais', label: 'Esportes - Jogos Medievais' },
  { value: 'esp-jojutso', label: 'Esportes - Jojutso' },
  { value: 'esp-judo', label: 'Esportes - Judô' },
  { value: 'esp-kali-filipino', label: 'Esportes - Kali Filipino' },
  { value: 'esp-karate', label: 'Esportes - Karatê' },
  { value: 'esp-kart', label: 'Esportes - Kart' },
  { value: 'esp-kendo', label: 'Esportes - Kendô' },
  { value: 'esp-kitesurf', label: 'Esportes - Kitesurf' },
  { value: 'esp-krav-maga', label: 'Esportes - Krav Magá' },
  { value: 'esp-kung-fu', label: 'Esportes - Kung-Fu' },
  { value: 'esp-lacador-corda', label: 'Esportes - Laçador de Corda' },
  { value: 'esp-parkour', label: 'Esportes - Le Parkour' },
  { value: 'esp-luta-greco-romana', label: 'Esportes - Luta Greco-Romana' },
  { value: 'esp-luta-livre', label: 'Esportes - Luta Livre' },
  { value: 'esp-mahamudra', label: 'Esportes - Mahamudra' },
  { value: 'esp-malabarismo-carro', label: 'Esportes - Malabarismo com Carro' },
  { value: 'esp-malabarismo-moto', label: 'Esportes - Malabarismo com Moto' },
  { value: 'esp-maratona', label: 'Esportes - Maratona' },
  { value: 'esp-mergulho-apneia', label: 'Esportes - Mergulho Apneia' },
  { value: 'esp-mergulho-cilindro', label: 'Esportes - Mergulho Cilindro' },
  { value: 'esp-mergulho-snorkel', label: 'Esportes - Mergulho Snorkel' },
  { value: 'esp-mma-fighting', label: 'Esportes - MMA Fighting' },
  { value: 'esp-mountain-bike', label: 'Esportes - Mountain Bike' },
  { value: 'esp-montanhismo', label: 'Esportes - Montanhismo' },
  {
    value: 'esp-moto-radical-acrobatico',
    label: 'Esportes - Moto (Radical/Acrobático)',
  },
  { value: 'esp-motocross', label: 'Esportes - Motocross' },
  { value: 'esp-motovelocidade', label: 'Esportes - Motovelocidade' },
  { value: 'esp-muay-thai', label: 'Esportes - Muay Thai' },
  { value: 'esp-musculacao', label: 'Esportes - Musculação' },
  { value: 'esp-nado-sincronizado', label: 'Esportes - Nado Sincronizado' },
  {
    value: 'esp-natacao-borboleta',
    label: 'Esportes - Natação - Nado Borboleta',
  },
  { value: 'esp-natacao-livre', label: 'Esportes - Natação - Nado Livre' },
  { value: 'esp-natacao-peito', label: 'Esportes - Natação - Nado Peito' },
  { value: 'esp-pancracio', label: 'Esportes - Pancrácio' },
  { value: 'esp-parapente-glider', label: 'Esportes - Parapente (Glider)' },
  { value: 'esp-paraquedismo', label: 'Esportes - Paraquedismo' },
  { value: 'esp-patinacao-artistica', label: 'Esportes - Patinação Artística' },
  { value: 'esp-patincao-gelo', label: 'Esportes - Patinação no Gelo' },
  { value: 'esp-patins-rodas', label: 'Esportes - Patins com rodas' },
  { value: 'esp-peao-rodeio', label: 'Esportes - Peão de Rodeio' },
  { value: 'esp-pesca-esportiva', label: 'Esportes - Pesca Esportiva' },
  { value: 'esp-peteca', label: 'Esportes - Peteca' },
  { value: 'esp-pilates', label: 'Esportes - Pilates' },
  { value: 'esp-polo-cavalo', label: 'Esportes - Polo a Cavalo' },
  { value: 'esp-polo-aquatico', label: 'Esportes - Polo Aquático' },
  { value: 'esp-rafting', label: 'Esportes - Rafting' },
  { value: 'esp-rapel', label: 'Esportes - Rapel' },
  { value: 'esp-remo', label: 'Esportes - Remo' },
  { value: 'esp-rugby', label: 'Esportes - Rugby' },
  { value: 'esp-salto-olimpico', label: 'Esportes - Salto (Olímpico)' },
  { value: 'esp-salto-vara', label: 'Esportes - Salto com Vara' },
  { value: 'esp-salto-penhasco', label: 'Esportes - Salto de Penhasco' },
  { value: 'esp-salto-altura', label: 'Esportes - Salto em Altura' },
  { value: 'esp-salto-distancia', label: 'Esportes - Salto em Distância' },
  { value: 'esp-savate', label: 'Esportes - Savate' },
  { value: 'esp-sinuca', label: 'Esportes - Sinuca' },
  { value: 'esp-skate-downhill', label: 'Esportes - Skate Downhill' },
  { value: 'esp-skate-freestyle', label: 'Esportes - Skate Freestyle' },
  { value: 'esp-skate-street', label: 'Esportes - Skate Street' },
  { value: 'esp-skate-vertical', label: 'Esportes - Skate Vertical' },
  { value: 'esp-ski-aquatico', label: 'Esportes - Ski Aquático' },
  { value: 'esp-ski-neve', label: 'Esportes - Ski na Neve' },
  { value: 'esp-skydive', label: 'Esportes - Skydive' },
  { value: 'esp-slackline', label: 'Esportes - Slackline' },
  { value: 'esp-snowboard', label: 'Esportes - Snowboard' },
  { value: 'esp-solo-olimpico', label: 'Esportes - Solo (Olímpico)' },
  { value: 'esp-squash', label: 'Esportes - Squash' },
  { value: 'esp-stand-up-paddle', label: 'Esportes - Stand-up Paddle' },
  { value: 'esp-sumo', label: 'Esportes - Sumô' },
  { value: 'esp-surf', label: 'Esportes - Surf' },
  { value: 'esp-taekwondo', label: 'Esportes - Taekwondo' },
  { value: 'esp-taichichuan', label: 'Esportes - Tai Chi Chuan' },
  { value: 'esp-tamboreu', label: 'Esportes - Tamboréu' },
  { value: 'esp-team-penning', label: 'Esportes - Team Penning' },
  { value: 'esp-tenis', label: 'Esportes - Tênis' },
  { value: 'esp-tenis-mesa', label: 'Esportes - Tênis de Mesa' },
  {
    value: 'esp-tiro-esportivo-carabina',
    label: 'Esportes - Tiro (Esportivo/Carabina)',
  },
  {
    value: 'esp-tiro-revolver-pistola',
    label: 'Esportes - Tiro (Revólver/Pistóla)',
  },
  { value: 'esp-tourada', label: 'Esportes - Tourada' },
  {
    value: 'esp-trampolim-salto-ornamental',
    label: 'Esportes - Trampolim (Salto Ornamental)',
  },
  { value: 'esp-trave-olimpica', label: 'Esportes - Trave Olímpica' },
  { value: 'esp-triathlon', label: 'Esportes - Triathlon' },
  { value: 'esp-trilha-4x4', label: 'Esportes - Trilha 4x4' },
  { value: 'esp-vale-tudo', label: 'Esportes - Vale-Tudo' },
  { value: 'esp-volei-praia', label: 'Esportes - Vôlei de Praia' },
  { value: 'esp-voleibol', label: 'Esportes - Voleibol' },
  { value: 'esp-voo-livre', label: 'Esportes - Vôo Livre' },
  { value: 'esp-wakeboard', label: 'Esportes - Wakeboard' },
  { value: 'esp-windsurf', label: 'Esportes - Windsurf' },
  { value: 'esp-wushu', label: 'Esportes - Wushu' },
  { value: 'esp-yoga', label: 'Esportes - Yoga' },
  { value: 'ins-acordeom', label: 'Instrumentos - Acordeom' },
  { value: 'ins-afoxe', label: 'Instrumentos - Afoxé' },
  { value: 'ins-agogo', label: 'Instrumentos - Agogô' },
  { value: 'ins-baixo', label: 'Instrumentos - Baixo' },
  { value: 'ins-bandolim', label: 'Instrumentos - Bandolim' },
  { value: 'ins-bateria', label: 'Instrumentos - Bateria' },
  { value: 'ins-berimbau	', label: 'Instrumentos - Berimbau' },
  { value: 'ins-castanhola', label: 'Instrumentos - Castanhola' },
  { value: 'ins-cavaquinho', label: 'Instrumentos - Cavaquinho' },
  { value: 'ins-chocalho', label: 'Instrumentos - Chocalho' },
  { value: 'ins-clarinete', label: 'Instrumentos - Clarinete' },
  { value: 'ins-clavineta', label: 'Instrumentos - Clavineta' },
  {
    value: 'ins-contrabaixoacustico',
    label: 'Instrumentos - Contrabaixo Acústico',
  },
  { value: 'ins-escaleta', label: 'Instrumentos - Escaleta' },
  { value: 'ins-fagote', label: 'Instrumentos - Fagote' },
  { value: 'ins-flauta', label: 'Instrumentos - Flauta' },
  { value: 'ins-flauta doce	', label: 'Instrumentos - Flauta Doce' },
  {
    value: 'ins-flauta transversal	',
    label: 'Instrumentos - Flauta Transversal',
  },
  { value: 'ins-flautim', label: 'Instrumentos - Flautim' },
  { value: 'ins-gaita', label: 'Instrumentos - Gaita' },
  { value: 'ins-guitarra', label: 'Instrumentos - Guitarra' },
  { value: 'ins-marimba', label: 'Instrumentos - Marimba' },
  { value: 'ins-moodlander', label: 'Instrumentos - Moodlander' },
  { value: 'ins-moodswinger', label: 'Instrumentos - Moodswinger' },
  { value: 'ins-pandeiro', label: 'Instrumentos - Pandeiro' },
  { value: 'ins-piano', label: 'Instrumentos - Piano' },
  { value: 'ins-pianoeletrico', label: 'Instrumentos - Piano elétrico' },
  { value: 'ins-rabeca', label: 'Instrumentos - Rabeca' },
  { value: 'ins-recoreco', label: 'Instrumentos - Reco Reco' },
  { value: 'ins-sanfona', label: 'Instrumentos - Sanfona' },
  { value: 'ins-saxofone	', label: 'Instrumentos - Saxofone' },
  { value: 'ins-tambor', label: 'Instrumentos - Tambor' },
  { value: 'ins-tamborim', label: 'Instrumentos - Tamborim' },
  { value: 'ins-teclado', label: 'Instrumentos - Teclado' },
  { value: 'ins-timpano', label: 'Instrumentos - Tímpano' },
  { value: 'ins-triangulo', label: 'Instrumentos - Triângulo' },
  { value: 'ins-trombeta', label: 'Instrumentos - Trombeta' },
  { value: 'ins-trombone	', label: 'Instrumentos - Trombone' },
  { value: 'ins-trompete	', label: 'Instrumentos - Trompete' },
  { value: 'ins-tuba', label: 'Instrumentos - Tuba' },
  { value: 'ins-ukulele', label: 'Instrumentos - Ukulele' },
  { value: 'ins-viola', label: 'Instrumentos - Viola' },
  { value: 'ins-violadegamba', label: 'Instrumentos - Viola de Gamba' },
  { value: 'ins-violao', label: 'Instrumentos - Violão' },
  { value: 'ins-violino', label: 'Instrumentos - Violino' },
  { value: 'ins-violoncelo', label: 'Instrumentos - Violoncelo' },
  { value: 'ins-xilofone', label: 'Instrumentos - Xilofone' },
];
